CREATE TABLE USERS(
	ID BIGINT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	GIVEN_NAME VARCHAR(100) NOT NULL,
	BIRTH_DATE TIMESTAMP DEFAULT NULL)/;
	
CREATE FUNCTION countUsers()
	RETURNS INTEGER READS SQL DATA
	BEGIN ATOMIC
		DECLARE nbUsers INTEGER;
		SET nbUsers = SELECT COUNT(*) FROM USERS U;
		RETURN nbUsers;
	END/;

CREATE FUNCTION countUsersWithIn(IN PARAM_IN INTEGER)
	RETURNS INTEGER READS SQL DATA
	BEGIN ATOMIC
		DECLARE nbUsers INTEGER;
		DECLARE incrementedNbUsers INTEGER;
		SET nbUsers = SELECT COUNT(*) FROM USERS U;
		SET incrementedNbUsers = nbUsers + PARAM_IN;
		RETURN incrementedNbUsers;
	END/;